# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Webstop's Grocery Website Style Guide
email: greg@webstop.com
description: > # this means to ignore newlines until "baseurl:"
  The definitive source of styling guidelines for grocery website features. Build using a simple and flexible collection of HTML5 & CSS3 frameworks for structure and style of user interface elements and components. Plus, Javascript plugins for compeling functionality and interactions.
baseurl: "" # the subpath of your site, e.g. /blog
bootstrap_docs_url: "/node_modules/bootstrap-docs/"
twitter_username: Hemphill
github_username:  Hemphill
host: 0.0.0.0

# Build settings
markdown:     kramdown
highlighter:  rouge
sass:
    sass_dir: assets/scss

# exclude notes: items past the line gap come from Bootstrap's devDependancies
# assets/scss,


exclude: [.git,
          .github,
          .idea,
          assets/scss,
          artifacts,
          bash,
          bash_node,
          build,
          build_docker.sh,
          docker-compose.yml,
          Dockerfile,
          Gemfile,
          Gemfile.lock,
          Gruntfile.js,
          README.md,
          package.json,
          package-lock.json,
          jekyll,
          js,
          NOTES.md,
          serve,
          setup,
          sinatra,
          update,
          vendor,
          watch,
          workspace,
          node_modules/bootstrap-docs/build,
          node_modules/bootstrap-docs/dist,
          node_modules/bootstrap-docs/Gemfile,
          node_modules/bootstrap-docs/LICENSE,
          node_modules/bootstrap-docs/package.json,
          node_modules/bootstrap-docs/README.md,
          node_modules/bootstrap-docs/scss,

          node_modules/@*,
          node_modules/ab*,
          node_modules/ac*,
          node_modules/ad*,
          node_modules/af*,
          node_modules/ag*,
          node_modules/aj*,
          node_modules/am*,
          node_modules/an*,
          node_modules/ap*,
          node_modules/ar*,
          node_modules/as*,
          node_modules/at*,
          node_modules/au*,
          node_modules/aw*,
          node_modules/ax*,
          node_modules/ba*,
          node_modules/bc*,
          node_modules/be*,
          node_modules/bh*,
          node_modules/bi*,
          node_modules/bl*,
          node_modules/bod*,
          node_modules/boom*,
          node_modules/box*,
          node_modules/by*,
          node_modules/br*,
          node_modules/bu*,
          node_modules/ca*,
          node_modules/cc*,
          node_modules/ce*,
          node_modules/ch*,
          node_modules/ci*,
          node_modules/cj*,
          node_modules/cl*,
          node_modules/cod*,
          node_modules/col*,
          node_modules/com*,
          node_modules/con*,
          node_modules/cop*,
          node_modules/core-j*,
          node_modules/core-u*,
          node_modules/co*,
          node_modules/cr*,
          node_modules/cs*,
          node_modules/cu*,
          node_modules/da*,
          node_modules/deb*,
          node_modules/dec*,
          node_modules/dee*,
          node_modules/def*,
          node_modules/deg*,
          node_modules/del*,
          node_modules/dep*,
          node_modules/det*,
          node_modules/det*,
          node_modules/dev-*,
          node_modules/di*,
          node_modules/do*,
          node_modules/du*,
          node_modules/e*,
          node_modules/f*,
          node_modules/g*,
          node_modules/h*,
          node_modules/i*,
          node_modules/jj*,
          node_modules/jo*,
          node_modules/js-*,
          node_modules/jsbarcode/a*,
          node_modules/jsbarcode/b*,
          node_modules/jsbarcode/C*,
          node_modules/jsbarcode/do*,
          node_modules/jsbarcode/Do*,
          node_modules/jsbarcode/e*,
          node_modules/jsbarcode/g*,
          node_modules/jsbarcode/M*,
          node_modules/jsbarcode/p*,
          node_modules/jsbarcode/R*,
          node_modules/jsbarcode/s*,
          node_modules/jsbarcode/t*,
          node_modules/jsbn*,
          node_modules/jse*,
          node_modules/jso*,
          node_modules/jsp*,
          node_modules/jsu*,
          node_modules/ju*,
          node_modules/k*,
          node_modules/l*,
          node_modules/m*,
          node_modules/n*,
          node_modules/o*,
          node_modules/p-*,
          node_modules/pa*,
          node_modules/pe*,
          node_modules/pi*,
          node_modules/pl*,
          node_modules/por*,
          node_modules/pos*,
          node_modules/pr*,
          node_modules/ps*,
          node_modules/pu*,
          node_modules/q*,
          node_modules/r*,
          node_modules/s*,
          node_modules/t*,
          node_modules/u*,
          node_modules/v*,
          node_modules/w*,
          node_modules/x*,
          node_modules/y*,
          node_modules/z*
          ]
