# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Webstop's Grocery Website Style Guide
email: greg@webstop.com
description: > # this means to ignore newlines until "baseurl:"
  The definitive source of styling guidelines for grocery website features. Build using a simple and flexible collection of HTML5 & CSS3 frameworks for structure and style of user interface elements and components. Plus, Javascript plugins for compeling functionality and interactions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: Hemphill
github_username:  Hemphill

# Build settings
markdown: kramdown
exclude: [Gemfile,
          Gemfile.lock,
          Gruntfile.js,
          README.md,
          grunt,
          package.json,
          workspace,
          node_modules/bootstrap-docs/CHANGELOG.md,
          node_modules/bootstrap-docs/dist,
          node_modules/bootstrap-docs/grunt,
          node_modules/bootstrap-docs/Gruntfile.js,
          node_modules/bootstrap-docs/LICENSE,
          node_modules/bootstrap-docs/package.json,
          node_modules/bootstrap-docs/README.md,
          node_modules/bootstrap-docs/scss,
          node_modules/jquery,
          node_modules/tether]


