# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Webstop's Grocery Website Style Guide
email: greg@webstop.com
description: > # this means to ignore newlines until "baseurl:"
  The definitive source of styling guidelines for grocery website features. Build using a simple and flexible collection of HTML5 & CSS3 frameworks for structure and style of user interface elements and components. Plus, Javascript plugins for compeling functionality and interactions.
baseurl: "" # the subpath of your site, e.g. /blog
bootstrap_docs_url: "/node_modules/bootstrap-docs/"
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: Hemphill
github_username:  Hemphill
host: 0.0.0.0

# Build settings
markdown: kramdown
sass:
    sass_dir: assets/scss
exclude: [build_docker.sh,
          Dockerfile,
          Gemfile,
          Gemfile.lock,
          Gruntfile.js,
          README.md,
          grunt,
          package.json,
          package-lock.json,
          jekyll,
          NOTES.md
          serve,
          watch,
          workspace,
          assets/scss,
          node_modules/bootstrap-docs/CHANGELOG.md,
          node_modules/bootstrap-docs/dist,
          node_modules/bootstrap-docs/grunt,
          node_modules/bootstrap-docs/Gruntfile.js,
          node_modules/bootstrap-docs/LICENSE,
          node_modules/bootstrap-docs/package.json,
          node_modules/bootstrap-docs/README.md,
          node_modules/bootstrap-docs/scss,




          node_modules/abbrev,
          node_modules/acorn,
          node_modules/acorn-jsx,
          node_modules/ajv,
          node_modules/ajv-keywords,
          node_modules/amdefine,
          node_modules/ansi-escapes,
          node_modules/ansi-regex,
          node_modules/ansi-styles,
          node_modules/anymatch,
          node_modules/aproba,
          node_modules/are-we-there-yet,
          node_modules/argparse,
          node_modules/arr-diff,
          node_modules/arr-flatten,
          node_modules/array-filter,
          node_modules/array-find-index,
          node_modules/array-map,
          node_modules/array-reduce,
          node_modules/array-union,
          node_modules/array-uniq,
          node_modules/array-unique,
          node_modules/arrify,
          node_modules/asap,
          node_modules/asn1,
          node_modules/assert-plus,
          node_modules/async-each,
          node_modules/async-foreach,
          node_modules/asynckit,
          node_modules/autoprefixer,
          node_modules/aws-sign2,
          node_modules/aws4,
          node_modules/babel-cli,
          node_modules/babel-code-frame,
          node_modules/babel-core,
          node_modules/babel-eslint,
          node_modules/babel-generator,
          node_modules/babel-helper-call-delegate,
          node_modules/babel-helper-define-map,
          node_modules/babel-helper-function-name,
          node_modules/babel-helper-get-function-arity,
          node_modules/babel-helper-hoist-variables,
          node_modules/babel-helper-optimise-call-expression,
          node_modules/babel-helper-regex,
          node_modules/babel-helper-replace-supers,
          node_modules/babel-helpers,
          node_modules/babel-messages,
          node_modules/babel-plugin-check-es2015-constants,
          node_modules/babel-plugin-transform-es2015-arrow-functions,
          node_modules/babel-plugin-transform-es2015-block-scoped-functions,
          node_modules/babel-plugin-transform-es2015-block-scoping,
          node_modules/babel-plugin-transform-es2015-classes,
          node_modules/babel-plugin-transform-es2015-computed-properties,
          node_modules/babel-plugin-transform-es2015-destructuring,
          node_modules/babel-plugin-transform-es2015-duplicate-keys,
          node_modules/babel-plugin-transform-es2015-for-of,
          node_modules/babel-plugin-transform-es2015-function-name,
          node_modules/babel-plugin-transform-es2015-literals,
          node_modules/babel-plugin-transform-es2015-modules-amd,
          node_modules/babel-plugin-transform-es2015-modules-commonjs,
          node_modules/babel-plugin-transform-es2015-modules-strip,
          node_modules/babel-plugin-transform-es2015-modules-systemjs,
          node_modules/babel-plugin-transform-es2015-modules-umd,
          node_modules/babel-plugin-transform-es2015-object-super,
          node_modules/babel-plugin-transform-es2015-parameters,
          node_modules/babel-plugin-transform-es2015-shorthand-properties,
          node_modules/babel-plugin-transform-es2015-spread,
          node_modules/babel-plugin-transform-es2015-sticky-regex,
          node_modules/babel-plugin-transform-es2015-template-literals,
          node_modules/babel-plugin-transform-es2015-typeof-symbol,
          node_modules/babel-plugin-transform-es2015-unicode-regex,
          node_modules/babel-plugin-transform-regenerator,
          node_modules/babel-plugin-transform-strict-mode,
          node_modules/babel-polyfill,
          node_modules/babel-preset-es2015,
          node_modules/babel-register,
          node_modules/babel-runtime,
          node_modules/babel-template,
          node_modules/babel-traverse,
          node_modules/babel-types,
          node_modules/babylon,
          node_modules/balanced-match,
          node_modules/bcrypt-pbkdf,
          node_modules/binary-extensions,
          node_modules/block-stream,
          node_modules/bluebird,
          node_modules/boom,
          node_modules/brace-expansion,
          node_modules/braces,
          node_modules/browserslist,
          node_modules/builtin-modules,
          node_modules/bulk-require,
          node_modules/caller-path,
          node_modules/callsites,
          node_modules/camelcase,
          node_modules/camelcase-keys,
          node_modules/caniuse-lite,
          node_modules/caseless,
          node_modules/chalk,
          node_modules/chokidar,
          node_modules/circular-json,
          node_modules/cjson,
          node_modules/clean-css,
          node_modules/clean-css-cli,
          node_modules/cli-cursor,
          node_modules/cli-spinners,
          node_modules/cli-width,
          node_modules/cliui,
          node_modules/co,
          node_modules/code-point-at,
          node_modules/combined-stream,
          node_modules/commander,
          node_modules/concat-map,
          node_modules/concat-stream,
          node_modules/configstore,
          node_modules/console-control-strings,
          node_modules/convert-source-map,
          node_modules/core-js,
          node_modules/core-util-is,
          node_modules/cosmiconfig,
          node_modules/cross-spawn,
          node_modules/cryptiles,
          node_modules/currently-unhandled,
          node_modules/d,
          node_modules/dashdash,
          node_modules/debug,
          node_modules/decamelize,
          node_modules/deep-extend,
          node_modules/deep-is,
          node_modules/define-properties,
          node_modules/del,
          node_modules/delayed-stream,
          node_modules/delegates,
          node_modules/dependency-graph,
          node_modules/detect-file,
          node_modules/detect-indent,
          node_modules/devicons,
          node_modules/doctrine,
          node_modules/dom-serializer,
          node_modules/domelementtype,
          node_modules/domhandler,
          node_modules/domutils,
          node_modules/duplexer,
          node_modules/duplexify,
          node_modules/oauth-sign,
          node_modules/object-assign,
          node_modules/object-keys,
          node_modules/object.omit,
          node_modules/once,
          node_modules/onetime,
          node_modules/optionator,
          node_modules/ora,
          node_modules/os-homedir,
          node_modules/os-locale,
          node_modules/os-tmpdir,
          node_modules/osenv,
          node_modules/output-file-sync,
          node_modules/p-finally,
          node_modules/p-limit,
          node_modules/p-locate,
          node_modules/package-json,
          node_modules/parse-filepath,
          node_modules/parse-glob,
          node_modules/parse-json,
          node_modules/parse-passwd,
          node_modules/path-exists,
          node_modules/path-is-absolute,
          node_modules/path-is-inside,
          node_modules/path-key,
          node_modules/path-parse,
          node_modules/path-root,
          node_modules/path-root-regex,
          node_modules/path-type,
          node_modules/pause-stream,
          node_modules/pend,
          node_modules/performance-now,
          node_modules/phantomjs-prebuilt,
          node_modules/pify,
          node_modules/pinkie,
          node_modules/pinkie-promise,
          node_modules/pluralize,
          node_modules/postcss,
          node_modules/postcss-cli,
          node_modules/postcss-flexbugs-fixes,
          node_modules/postcss-load-config,
          node_modules/postcss-load-options,
          node_modules/postcss-load-plugins,
          node_modules/postcss-reporter,
          node_modules/postcss-value-parser,
          node_modules/prelude-ls,
          node_modules/prepend-http,
          node_modules/preserve,
          node_modules/private,
          node_modules/process-nextick-args,
          node_modules/progress,
          node_modules/promise,
          node_modules/ps-tree,
          node_modules/pseudomap,
          node_modules/punycode,
          node_modules/randomatic,
          node_modules/rc,
          node_modules/read-all-stream,
          node_modules/read-cache,
          node_modules/read-pkg,
          node_modules/read-pkg-up,
          node_modules/readable-stream,
          node_modules/readdirp,
          node_modules/readline2,
          node_modules/rechoir,
          node_modules/redent,
          node_modules/regenerate,
          node_modules/regenerator-runtime,
          node_modules/regenerator-transform,
          node_modules/regex-cache,
          node_modules/regexpu-core,
          node_modules/registry-url,
          node_modules/regjsgen,
          node_modules/regjsparser,
          node_modules/remove-trailing-separator,
          node_modules/repeat-element,
          node_modules/repeat-string,
          node_modules/repeating,
          node_modules/request,
          node_modules/request-progress,
          node_modules/require-directory,
          node_modules/require-from-string,
          node_modules/require-main-filename,
          node_modules/require-uncached,
          node_modules/resolve,
          node_modules/resolve-dir,
          node_modules/resolve-from,
          node_modules/restore-cursor,
          node_modules/rimraf,
          node_modules/run-async,
          node_modules/rx-lite,
          node_modules/safe-buffer,
          node_modules/sass-graph,
          node_modules/scss-tokenizer,
          node_modules/semver,
          node_modules/semver-diff,
          node_modules/set-blocking,
          node_modules/set-immediate-shim,
          node_modules/shebang-command,
          node_modules/shebang-regex,
          node_modules/shell-quote,
          node_modules/shelljs,
          node_modules/shx,
          node_modules/sigmund,
          node_modules/signal-exit,
          node_modules/slash,
          node_modules/slice-ansi,
          node_modules/slide,
          node_modules/sntp,
          node_modules/source-map,
          node_modules/source-map-support,
          node_modules/spdx-correct,
          node_modules/spdx-expression-parse,
          node_modules/spdx-license-ids,
          node_modules/split,
          node_modules/sprintf-js,
          node_modules/sshpk,
          node_modules/stdout-stream,
          node_modules/stream-combiner,
          node_modules/stream-shift,
          node_modules/string_decoder,
          node_modules/string-length,
          node_modules/string-width,
          node_modules/string.prototype.padend,
          node_modules/stringstream,
          node_modules/strip-ansi,
          node_modules/strip-bom,
          node_modules/strip-eof,
          node_modules/strip-indent,
          node_modules/strip-json-comments,
          node_modules/supports-color,
          node_modules/table,
          node_modules/tar,
          node_modules/text-table,
          node_modules/throttleit,
          node_modules/through,
          node_modules/timed-out,
          node_modules/to-fast-properties,
          node_modules/touch,
          node_modules/tough-cookie,
          node_modules/trim-newlines,
          node_modules/trim-right,
          node_modules/tryit,
          node_modules/tunnel-agent,
          node_modules/tweetnacl,
          node_modules/type-check,
          node_modules/typedarray




          ]
